### ISSUE TITLE
how does this without userparameters ?

### ISSUE THREAD

**Issue by SinghDivneet** [viniciusbo/zabbix-emqtt#1]
Isn't there supposed to be a shell script & command in the `agent.conf` ?

**Comment by viniciusbo** [comment]
Actually not. You can read more here https://www.zabbix.com/documentation/3.0/manual/config/items/itemtypes/external and here https://www.zabbix.com/documentation/3.0/manual/concepts/sender.

**Comment by viniciusbo** [comment]
Closing this issue. Please feel free to reopen this issue if you have any more questions.
