### ISSUE TITLE
Cannot index array with string "result".

### ISSUE THREAD

**Issue by Zziwen** [viniciusbo/zabbix-emqtt#2]
jq: error (at <stdin>:1): Cannot index array with string "result"
what is the reason for this?

My MQTT version is 3.0
My configuration: 
stats=$(curl --basic -u "$2:$3" -k -s "http://$4:18083/api/v3/stats/")
metrics=$(curl --basic -u "$2:$3" -k -s "http://$4:18083/api/v3/metrics/")

for key in "${STATS_KEYS[@]}"
do
  out="$(jq -r --arg arg "$(printf '%s' $key)" '.result[]|.["emq@'"$1"'"]? | .[$arg]' <<< $stats)"
  # printf "%s %s\n" $key $out
  zabbix_sender -z 127.0.0.1 -s $1 -k "emqtt[$key]" -o $out > /dev/null 2>&1
done

for key in "${METRICS_KEYS[@]}"
do
  out="$(jq -r --arg arg "$(printf '%s' $key)" '.result[]|.["emq@'"$1"'"]? | .[$arg]' <<< $metrics)"
  # printf "%s %s\n" $key $out
  zabbix_sender -z 127.0.0.1 -s $1 -k "emqtt[$key]" -o $out > /dev/null 2>&1
done

**Comment by viniciusbo** [comment]
Are STATS_KEYS and METRICS_KEYS also set?
